export { default as departmentsRoutes } from './departmentRoutes.js';
export { default as employeeRoutes } from './employeeRoutes.js';
export { default as intercomRoutes } from './intercomRoutes.js';
export { default as logRoutes } from './logRoutes.js'
export { default as multiCallRingingRoutes } from './multiCallRingingRoutes.js';
export { default as regularAnexRoutes } from './regularAnexRoute.js';
export { default as restrictionsRoutes } from './restrictionRoutes.js';
export { default as roleRoutes } from './roleRoutes.js';
export { default as statusRoutes } from './statusRoutes.js';
export { default as transportTypesRoutes } from './transportTypeRoutes.js';
export { default as troncalRoutes } from './troncalRoutes.js'
